# Generated by Django 5.0.6 on 2024-07-02 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ninja_api', '0002_category_country_district_expirience_keyword_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='many_category',
            field=models.ManyToManyField(blank=True, to='ninja_api.manycategory'),
        ),
    ]
