# Generated by Django 5.0.6 on 2024-07-02 11:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ninja_api', '0003_alter_job_many_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='expirience',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ninja_api.expirience'),
        ),
    ]
