# Generated by Django 5.0.6 on 2024-07-02 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ninja_api', '0004_job_expirience'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='name',
        ),
    ]
