# Generated by Django 5.0.6 on 2024-07-02 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ninja_api', '0005_remove_job_name'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Type',
            new_name='CompanyType',
        ),
        migrations.RenameField(
            model_name='company',
            old_name='type',
            new_name='company_type',
        ),
        migrations.RenameField(
            model_name='job',
            old_name='phone',
            new_name='phone_one',
        ),
        migrations.RemoveField(
            model_name='job',
            name='email',
        ),
        migrations.AddField(
            model_name='job',
            name='email_one',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='email_three',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='email_two',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='exact_location',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='job_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='phone_three',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='phone_two',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
    ]
