# Generated by Django 5.0.6 on 2024-07-02 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ninja_api', '0006_rename_type_companytype_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='phone_one',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='phone_three',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='phone_two',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='whatsapp',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
