# Generated by Django 5.0.6 on 2024-07-02 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ninja_api', '0007_alter_job_phone_one_alter_job_phone_three_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='name',
            field=models.CharField(default=1, max_length=50),
        ),
    ]
