# Generated by Django 5.0.6 on 2024-07-02 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ninja_api', '0009_alter_job_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='closing_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='posted',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
