# Generated by Django 5.0.6 on 2024-07-02 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ninja_api', '0010_job_closing_date_job_posted'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='exact_location',
            new_name='address',
        ),
        migrations.AddField(
            model_name='company',
            name='address',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
