# Generated by Django 5.0.6 on 2024-07-05 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ninja_api', '0011_rename_exact_location_job_address_company_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image_url',
            field=models.CharField(blank=True, max_length=550, null=True),
        ),
    ]
