# Generated by Django 5.0.6 on 2024-07-06 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ninja_api', '0013_alter_category_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='name',
            field=models.CharField(max_length=500),
        ),
    ]
