# Generated by Django 5.0.6 on 2024-07-06 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ninja_api', '0015_alter_job_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='image_url',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='company',
            name='address',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='facebook',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='google_map',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='instagram',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='website',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='companytype',
            name='name',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='country',
            name='name',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='district',
            name='name',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='job',
            name='address',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='source',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='keyword',
            name='name',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='manycategory',
            name='name',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='state',
            name='name',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='name',
            field=models.CharField(max_length=500),
        ),
    ]
