# Generated by Django 5.0.6 on 2024-07-06 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ninja_api', '0017_alter_company_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
    ]
