# Generated by Django 5.0.6 on 2024-07-06 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ninja_api', '0018_alter_job_address'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Expirience',
            new_name='Experience',
        ),
        migrations.RenameField(
            model_name='job',
            old_name='expirience',
            new_name='experience',
        ),
        migrations.RemoveField(
            model_name='job',
            name='category',
        ),
        migrations.AddField(
            model_name='job',
            name='category',
            field=models.ManyToManyField(blank=True, to='ninja_api.category'),
        ),
    ]
