# Generated by Django 5.0.6 on 2024-07-06 10:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ninja_api', '0019_rename_expirience_experience_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='experience',
        ),
        migrations.RemoveField(
            model_name='job',
            name='keyword',
        ),
        migrations.RemoveField(
            model_name='manycategory',
            name='sub_category',
        ),
        migrations.RemoveField(
            model_name='job',
            name='many_category',
        ),
        migrations.RemoveField(
            model_name='subcategory',
            name='category',
        ),
        migrations.RemoveField(
            model_name='job',
            name='sub_category',
        ),
        migrations.RemoveField(
            model_name='job',
            name='email_one',
        ),
        migrations.RemoveField(
            model_name='job',
            name='email_three',
        ),
        migrations.RemoveField(
            model_name='job',
            name='email_two',
        ),
        migrations.RemoveField(
            model_name='job',
            name='job_type',
        ),
        migrations.RemoveField(
            model_name='job',
            name='phone_one',
        ),
        migrations.RemoveField(
            model_name='job',
            name='phone_three',
        ),
        migrations.RemoveField(
            model_name='job',
            name='phone_two',
        ),
        migrations.RemoveField(
            model_name='job',
            name='whatsapp',
        ),
        migrations.AddField(
            model_name='company',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='jobs'),
        ),
        migrations.AddField(
            model_name='job',
            name='image_url',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='max_years_experience',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='min_years_experience',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='name',
            field=models.CharField(max_length=500, unique=True),
        ),
        migrations.CreateModel(
            name='ItPark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500, unique=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ninja_api.district')),
            ],
        ),
        migrations.AddField(
            model_name='job',
            name='itpark',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ninja_api.itpark'),
        ),
        migrations.DeleteModel(
            name='Experience',
        ),
        migrations.DeleteModel(
            name='Keyword',
        ),
        migrations.DeleteModel(
            name='ManyCategory',
        ),
        migrations.DeleteModel(
            name='SubCategory',
        ),
    ]
