# Generated by Django 5.0.6 on 2024-07-06 12:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ninja_api', '0021_subcategory_remove_job_category_job_sub_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subcategory',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ninja_api.category'),
        ),
    ]
