# Generated by Django 5.0.6 on 2024-07-06 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ninja_api', '0022_subcategory_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itpark',
            name='name',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='job',
            name='image_url',
            field=models.CharField(blank=True, max_length=1500, null=True),
        ),
    ]
